### ISSUE TITLE
Ui가 디렉토리 주소를 가져오지 못 합니다.

### ISSUE THREAD

**Issue by ham7562** [ham7562/gitTfTest#1]
디렉토리 주소를 가져와 텍스트 레이블에 넣고 텍스트 레이블에서 해당값을 가져오는 코드가 필요합니다.

또 에러 발생확인 코드도 필요하구요

**Comment by jgun456** [comment]
QT 디자이너로 UI생성, 변환한 코드에서 Q파일 로그가 작동하지 않고 꺼지는 증상이 발생합니다

**Comment by ham7562** [comment]
관련 문제에 대해서 해결방법을 찾지 못하였고, 따로 디자이너 프로그램을 사용하지 않고 코드로 작성하여 생성한 샘플 GUI는 정상 작동했습니다.
이에 수작업으로 새로 작성이 필요합니다.

**Comment by ham7562** [comment]
해당 문제의 경우 QtWidgets. 문장이 빠진 간단한 문제였으며 오류가 검출되지 않아 찾기가 매우 힘들었습니다.
어제 수정하여 업로드 하였으며 브런치를 나눠 ui를 작업하겠습니다.
